USE master;
GO
ALTER DATABASE NHH_VANPHONGPHAM SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
GO

DROP DATABASE IF EXISTS NHH_VANPHONGPHAM;

CREATE DATABASE NHH_VANPHONGPHAM;
go
USE NHH_VANPHONGPHAM;
go

CREATE TABLE tbDANHMUCVANPHONGPHAM (
    MALOAI INT PRIMARY KEY NOT NULL,
    TENLOAI NVARCHAR(20),
    MOTA NVARCHAR(MAX)
);

CREATE TABLE tbVANPHONGPHAM (
    MAVANPHONGPHAM INT PRIMARY KEY NOT NULL,
    TENVANPHONGPHAM NVARCHAR(200),
    MOTA NVARCHAR(MAX),
    MALOAI INT FOREIGN KEY REFERENCES tbDANHMUCVANPHONGPHAM(MALOAI)
		On update 
			cascade
		On delete
			cascade,
);

insert into tbDANHMUCVANPHONGPHAM (MALOAI, TENLOAI, MOTA)
values 
	(1,N'Giấy in văn phòng',NULL),
	(2,N'Bút lông viết bảng',NULL),
	(3,N'Sổ-tập tài liệu',NULL),
	(4,N'Gôm-bút tẩy xóa',NULL),
	(5,N'Dao kéo, băng keo',NULL);

insert into tbVANPHONGPHAM (MAVANPHONGPHAM, TENVANPHONGPHAM, MOTA)
values 
	(1,N'Bút lông viết bảng Thiên Long',NULL),
	(2,N'Giấy in hiệu Tuyết Mai',NULL);

-- Stored procedures for the VANPHONGPHAM database

-- Get all categories
CREATE PROCEDURE sp_GetAllDanhMuc
AS
BEGIN
    SELECT MALOAI, TENLOAI, MOTA FROM tbDANHMUCVANPHONGPHAM
END
GO

-- Get category by ID
CREATE PROCEDURE sp_GetDanhMucById
    @MALOAI int
AS
BEGIN
    SELECT MALOAI, TENLOAI, MOTA FROM tbDANHMUCVANPHONGPHAM WHERE MALOAI = @MALOAI
END
GO

-- Get category by name
CREATE PROCEDURE sp_GetDanhMucByName
    @TENLOAI nvarchar(20)
AS
BEGIN
    SELECT MALOAI, TENLOAI, MOTA FROM tbDANHMUCVANPHONGPHAM WHERE TENLOAI = @TENLOAI
END
GO

-- Get all office supplies
CREATE PROCEDURE sp_GetAllVanPhongPham
AS
BEGIN
    SELECT MAVANPHONGPHAM, TENVANPHONGPHAM, MOTA, MALOAI FROM tbVANPHONGPHAM
END
GO

-- Get office supply by ID
CREATE PROCEDURE sp_GetVanPhongPhamById
    @MAVANPHONGPHAM int
AS
BEGIN
    SELECT MAVANPHONGPHAM, TENVANPHONGPHAM, MOTA, MALOAI FROM tbVANPHONGPHAM 
    WHERE MAVANPHONGPHAM = @MAVANPHONGPHAM
END
GO

-- Add a new office supply
CREATE PROCEDURE sp_ThemVanPhongPham
    @TENVANPHONGPHAM nvarchar(200),
    @MALOAI int,
    @MOTA nvarchar(max)
AS
BEGIN
    INSERT INTO tbVANPHONGPHAM (TENVANPHONGPHAM, MALOAI, MOTA)
    VALUES (@TENVANPHONGPHAM, @MALOAI, @MOTA)
END
GO

-- Update an office supply
CREATE PROCEDURE sp_SuaVanPhongPham
    @MAVANPHONGPHAM int,
    @TENVANPHONGPHAM nvarchar(200),
    @MALOAI int,
    @MOTA nvarchar(max)
AS
BEGIN
    UPDATE tbVANPHONGPHAM
    SET TENVANPHONGPHAM = @TENVANPHONGPHAM,
        MALOAI = @MALOAI,
        MOTA = @MOTA
    WHERE MAVANPHONGPHAM = @MAVANPHONGPHAM
END
GO

-- Delete an office supply
CREATE PROCEDURE sp_XoaVanPhongPham
    @MAVANPHONGPHAM int
AS
BEGIN
    DELETE FROM tbVANPHONGPHAM
    WHERE MAVANPHONGPHAM = @MAVANPHONGPHAM
END
GO

-- Search for office supplies
CREATE PROCEDURE sp_TimVanPhongPham
    @KEYWORD nvarchar(200)
AS
BEGIN
    SELECT MAVANPHONGPHAM, TENVANPHONGPHAM, MOTA, MALOAI FROM tbVANPHONGPHAM
    WHERE TENVANPHONGPHAM LIKE N'%' + @KEYWORD + N'%'
    OR MOTA LIKE N'%' + @KEYWORD + N'%'
END
GO